### PR TITLE
Added Sending Queued Commands to Bridge Functions

### PR DESCRIPTION
**Pull request by ozgucbertug**
Hey Ardavan! Here's the edited code for Machina-Python. I've added my name but feel free to change that :)

### CODE REVIEW

**Comment by garciadelcastillo** [comment]
Hi @ozgucbertug, and thanks for your contribution! 
What is the purpose of the new `queue...` flavor for Actions? What's the difference between a regular and queued action?

**Comment by ozgucbertug** [comment]
Hi @garciadelcastillo. I figured out that current implementation actually opens and closes the connection to the web socket on each command push. In many cases, this resulted in Machina Bridge crashing if you wanted to push 100 or more move targets within a loop, which I assume is due to a lot of connections being opened and closed in a short period of time. I've changed the code so that you can queue the commands in a list and push them all to the bridge at once. This proved to be very useful for my on-going research setup and wanted to share it with you and @Ardibid.

**Comment by garciadelcastillo** [comment]
That sounds great, and I agree with you in that it sounds like the overall desirable behavior of the Py library. 

Why not change the overall behavior of the entire library, and just establish a permanent WS client connection to the Bridge, that can be used to send/receive action requests? This is how other client applications work, such as for example GH, Dynamo and the Processing libraries. Connections and their parameters could be controlled with `connect` and `disconnect` actions, and any time an action is requested, a push is sent to the Bridge. 

This sounds like a better architecture for the library, and more consistent with the other projects in the ecosystem. Furthermore, it avoids needing to maintain two parallel APIs for each action, i.e. the basic flavor and the queued one: it is very unlikely that if an user knows of the difference, s/he will be switching between behaviors, but rather stick to one or the other. If there was a strong reason to maintain the "non-permanent connection" mode, this could be internally controlled with yet another action, such as `queueMode(...)`. 

How does this sound @ozgucbertug ? :)

**Comment by ozgucbertug** [comment]
The reason I've implemented the "non-permanent connection" was actually to block the communication until a certain condition is met. I definitely think that having a permanent connection is a better way to implement it, and this would actually enable the user to continuously stream feedback data as well. I'll try to look into it, most probably after my thesis is submitted, and share it with you guys :)

**Comment by garciadelcastillo** [comment]
I see. Well, happy to keep the conversation going, and if you want to submit an improved version, I'd be happy to discuss it and incorporate it to the main repo ;)

Goo luck with your thesis, and don't let @Ardibid give you a tough time! lol

**Pull request closed without merging**
